name: My First Workflow
on: 
  workflow_dispatch: 
env: 
  first_name: MONA
jobs:
  My_First_Job:
    env:
      second_name: RONA
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
        
      - name: Printing Greeting Message
        run: echo "Hello $first_name tum $second_name"
        
      - name: Listing Files
        run: ls -a | wc -l 
