name: My Workflow For Terraform
on:
  push:
    branches:
      - main
      - devlop
jobs:
  My_First_Terraform_Job:
    name: My First Terraform Job
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: hashicorp/setup-terraform@v4
       with:
         terraform_version: "1.14.6"
        
    
    
